config/routes.rb
Rails.application.routes.draw do
  resources :birds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
class Bird < ApplicationRecord
    has_many :eggs , inverse_of: :bird
    accepts_nested_attributes_for :eggs
    validates :name , :family , presence: true
end

app/models/egg.rb
class Egg < ApplicationRecord
    belongs_to :bird
    validates :count , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: [:show, :edit, :update, :destroy]

  # GET /birds
  # GET /birds.json
  def index
    @birds = Bird.all
  end

  # GET /birds/1
  # GET /birds/1.json
  def show
      @eggs = Egg.find_by(bird_id: set_bird.id)
  end

  # GET /birds/new
  def new
    @bird = Bird.new
    @egg = @bird.eggs.build
  end

  # GET /birds/1/edit
  def edit
  end

  # POST /birds
  # POST /birds.json
  def create
    @bird = Bird.new(bird_params)

    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birds/1
  # PATCH/PUT /birds/1.json
  def update
    respond_to do |format|
      if @bird.update(bird_params)
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { render :show, status: :ok, location: @bird }
      else
        format.html { render :edit }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birds/1
  # DELETE /birds/1.json
  def destroy
    @bird.destroy
    respond_to do |format|
      format.html { redirect_to birds_url, notice: 'Bird was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def bird_params
      params
        .require(:bird)
        .permit(:name, :family, eggs_attributes: [:count])
    end
   # Never trust parameters from the scary internet, only allow the white list through.
    def set_bird
      @bird = Bird.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/_form.html.haml
= simple_form_for(@bird) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :family
    = f.simple_fields_for :eggs do |e|
      = e.input :count
  .form-actions
    = f.button :submit

app/views/birds/edit.html.haml
%h1 Editing bird

= render 'form'

= link_to 'Show', @bird
\|
= link_to 'Back', birds_path

app/views/birds/index.html.haml
%h1 Listing birds

%table
  %thead
    %tr
      %th Name
      %th Family
      %th
      %th
      %th

  %tbody
    - @birds.each do |bird|
      %tr
        %td= bird.name
        %td= bird.family
        %td= link_to 'Show', bird
        %td= link_to 'Edit', edit_bird_path(bird)
        %td= link_to 'Destroy', bird, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bird', new_bird_path

app/views/birds/new.html.haml
%h1 New bird

= render 'form'

= link_to 'Back', birds_path

app/views/birds/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bird.name
%p
  %b Family:
  = @bird.family
%p
  %b Eggs count
  - if @bird.family.downcase == "cobblepot"
    = "I don't lay eggs you bloody developer, but the count is  #{@eggs.count} "
  - else
    = @eggs.count

= link_to 'Edit', edit_bird_path(@bird)
\|
= link_to 'Back', birds_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Nest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield